{
  "formatVersion": "1.1",
  "component": {
    "group": "meteordevelopment",
    "module": "NBT",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "NBT-0.1.3.jar",
          "url": "NBT-0.1.3.jar",
          "size": 31134,
          "sha512": "4f01e9b1710644faffd4275c2bc96d1d4cfa58b98a384e54a7e32ebf651d9c27c32df03df6cfd2379d5127007f0c4e87e3643887cd98d57762ea120bd86d9bac",
          "sha256": "10e2e9472fbd6a83aba7fd590ce6c390dc58003285d45feb8c4a7ab05f5224e8",
          "sha1": "f671eb8b980fb3a26e2f2e40c4d7bf0e5a18d8fd",
          "md5": "276e1e310dd88ce3611c7212a2a0f1d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NBT-0.1.3.jar",
          "url": "NBT-0.1.3.jar",
          "size": 31134,
          "sha512": "4f01e9b1710644faffd4275c2bc96d1d4cfa58b98a384e54a7e32ebf651d9c27c32df03df6cfd2379d5127007f0c4e87e3643887cd98d57762ea120bd86d9bac",
          "sha256": "10e2e9472fbd6a83aba7fd590ce6c390dc58003285d45feb8c4a7ab05f5224e8",
          "sha1": "f671eb8b980fb3a26e2f2e40c4d7bf0e5a18d8fd",
          "md5": "276e1e310dd88ce3611c7212a2a0f1d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NBT-0.1.3-sources.jar",
          "url": "NBT-0.1.3-sources.jar",
          "size": 12965,
          "sha512": "6fa4509218b256e5db7689fc08ed813b5dde298c4050bec2b3a7451e5c5c3be18cb1a5ebd138b591426b0e4e98303c8194b07382fd7d3dab6324af4655be206a",
          "sha256": "fdd92f73e7146a873815c830ddd44703aef8cecf33136f38d96015a723a9f23b",
          "sha1": "17af5823f316fff39adb050619f4de7e73bd6fa3",
          "md5": "eab60877b27ee983074ecbf154a54274"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NBT-0.1.3-javadoc.jar",
          "url": "NBT-0.1.3-javadoc.jar",
          "size": 164369,
          "sha512": "68252fad97e5f53fa21fe037cb2ab1b1b97b8115d9f3bc117e512d62c65f72c5eb3834bb41b6e7b0115ad7ae3cdfd307de487cdafaf871d81141212ab5f812d3",
          "sha256": "3619561cfa4e7593c605d8366260cf424281df829c7fbf9f491f6b39a908db99",
          "sha1": "9978b6fc927b48ebb35b582e3a4552636eae24de",
          "md5": "09acd497bca9caccebaeaa3703b260b3"
        }
      ]
    }
  ]
}
